import { useEffect, useRef, useState } from "react";
import type { FormEvent } from "react";
import { Link, useNavigate, useParams } from "react-router";
import { FiArrowUp, FiBookOpen, FiFileText, FiMessageSquare, FiPlus } from "react-icons/fi";
import type { StudyChat, StudyData } from "../data/mockData";
import { askQuestion, createChat, getStudyData } from "../services/mockBackend";

export default function Chat() {
     const { chatId } = useParams(); const navigate = useNavigate(); const [data, setData] = useState<StudyData | null>(null); const [active, setActive] = useState<StudyChat | null>(null); const [question, setQuestion] = useState(""); const [sending, setSending] = useState(false); const bottom = useRef<HTMLDivElement>(null);
     useEffect(() => { let mounted = true; void getStudyData().then((next) => { if (mounted) { setData(next); setActive(next.chats.find((chat) => chat.id === chatId) ?? null); } }); return () => { mounted = false; }; }, [chatId]);
     useEffect(() => { bottom.current?.scrollIntoView({ behavior: "smooth" }); }, [active?.messages.length, sending]);
     const startChat = async () => { const chat = await createChat(); navigate(`/chat/${chat.id}`); };
     const submit = async (event: FormEvent) => { event.preventDefault(); if (!question.trim() || sending) return; const prompt = question.trim(); setQuestion(""); setSending(true); let id = chatId; if (!id) { const created = await createChat(); id = created.id; navigate(`/chat/${id}`, { replace: true }); } try { const next = await askQuestion(id, prompt); setActive(next); setData(await getStudyData()); } finally { setSending(false); } };
     return <div className="flex min-h-full"><aside className="hidden w-64 shrink-0 border-r border-cardBorder bg-cardBg p-4 md:block"><button onClick={() => void startChat()} className="flex w-full items-center justify-center gap-2 rounded-lg bg-short px-4 py-2.5 text-sm font-semibold text-background"><FiPlus /> New chat</button><p className="mb-2 mt-7 px-2 text-xs font-medium uppercase tracking-wider">Recent chats</p><div className="space-y-1">{data?.chats.map((chat) => <Link key={chat.id} to={`/chat/${chat.id}`} className={`flex items-center gap-2 rounded-lg px-3 py-2 text-sm ${chat.id === chatId ? "bg-dashBg text-title ring-1 ring-cardBorder" : "hover:bg-navB"}`}><FiMessageSquare className="shrink-0" /><span className="truncate">{chat.title}</span></Link>)}</div><Link to="/documents" className="mt-7 flex items-center gap-2 rounded-lg px-3 py-2 text-sm hover:bg-navB"><FiFileText /> Browse documents</Link></aside>
          <section className="flex min-w-0 flex-1 flex-col"><header className="border-b border-cardBorder px-5 py-4 sm:px-8"><p className="text-xs font-medium uppercase tracking-[0.16em] text-short">Study chat</p><h1 className="mt-1 truncate text-xl font-medium text-title">{active?.title ?? "Ask your study materials"}</h1></header>
               <div className="flex-1 overflow-y-auto px-4 py-6 sm:px-8"><div className="mx-auto max-w-3xl space-y-7">{active?.messages.length ? active.messages.map((message) => <article key={message.id} className={message.role === "user" ? "ml-auto max-w-[85%] rounded-2xl rounded-br-sm bg-short/10 px-4 py-3 text-title" : "max-w-3xl"}>{message.role === "assistant" && <div className="mb-2 flex items-center gap-2 text-sm font-semibold text-title"><span className="grid size-6 place-items-center rounded-md bg-short text-xs text-background">S</span>Study Buddy</div>}<p className="whitespace-pre-wrap leading-relaxed">{message.content}</p>{message.citations?.map((citation, index) => <div key={`${message.id}-${index}`} className="mt-3 inline-flex items-center gap-2 rounded-lg border border-cardBorder bg-dashBg px-3 py-2 text-xs"><FiBookOpen className="text-short" /><span className="font-medium text-title">{citation.documentName}</span><span>Page {citation.page} · {citation.topic}</span></div>)}</article>) : <div className="mx-auto max-w-xl py-16 text-center"><span className="mx-auto grid size-14 place-items-center rounded-2xl bg-short/10 text-2xl text-short"><FiBookOpen /></span><h2 className="mt-5 text-2xl font-medium text-title">Study with your own materials</h2><p className="mt-2">Ask a question below. Answers use your ready documents and include page references.</p><div className="mt-6 flex flex-wrap justify-center gap-2">{["Explain round-robin scheduling", "Summarize my latest notes", "What should I revise first?"] .map((prompt) => <button key={prompt} onClick={() => setQuestion(prompt)} className="rounded-full border border-cardBorder px-3 py-2 text-sm hover:border-short/50 hover:text-title">{prompt}</button>)}</div>{!data?.documents.some((doc) => doc.status === "ready") && <Link to="/documents" className="mt-5 inline-block text-sm font-medium text-short hover:underline">Upload a PDF to get started</Link>}</div>}{sending && <div className="text-sm text-muted">Study Buddy is looking through your materials…</div>}<div ref={bottom} /></div></div>
               <form onSubmit={(e) => void submit(e)} className="border-t border-cardBorder bg-background p-4 sm:px-8"><div className="mx-auto flex max-w-3xl items-end gap-2 rounded-xl border border-cardBorder bg-dashBg p-2 focus-within:border-short"><textarea value={question} onChange={(e) => setQuestion(e.target.value)} onKeyDown={(e) => { if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); e.currentTarget.form?.requestSubmit(); } }} rows={1} placeholder="Ask about your study material…" className="max-h-32 min-h-10 flex-1 resize-y bg-transparent px-2 py-2 text-sm text-title outline-none placeholder:text-muted" /><button disabled={!question.trim() || sending} aria-label="Send question" className="grid size-10 shrink-0 place-items-center rounded-lg bg-short text-lg text-background hover:opacity-90 disabled:opacity-40"><FiArrowUp /></button></div><p className="mx-auto mt-2 max-w-3xl text-xs">Demo answers are generated from sample metadata. Verify important details in the source.</p></form>
          </section>
     </div>;
}
