import { useEffect, useState } from "react";
import { Link } from "react-router";
import { FiArrowRight, FiBookOpen, FiFileText, FiMessageSquare, FiPlus, FiUpload } from "react-icons/fi";
import { useAuth } from "../hooks/useAuth";
import { getStudyData } from "../services/mockBackend";
import type { StudyData } from "../data/mockData";

function getGreeting() { const hour = new Date().getHours(); return hour < 12 ? "Good morning" : hour < 18 ? "Good afternoon" : "Good evening"; }
function relativeTime(iso: string) { const days = Math.floor((Date.now() - new Date(iso).getTime()) / 86_400_000); return days < 1 ? "Today" : days === 1 ? "Yesterday" : `${days} days ago`; }

export default function Dashboard() {
     const { user } = useAuth(); const [data, setData] = useState<StudyData | null>(null);
     useEffect(() => { void getStudyData().then(setData); }, []);
     const docs = data?.documents ?? []; const chats = data?.chats ?? []; const ready = docs.filter((d) => d.status === "ready").length; const processing = docs.filter((d) => d.status === "processing").length;
     return <div className="mx-auto max-w-5xl px-5 py-10 sm:px-8"><section className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-sm font-medium uppercase tracking-[0.16em] text-short">Your study space</p><h1 className="mt-2 text-3xl font-medium tracking-tight text-title sm:text-4xl">{getGreeting()}, {user?.name?.split(" ")[0] ?? "there"}.</h1><p className="mt-2 text-lg">What would you like to study today?</p></div><Link to="/chat" className="flex items-center gap-2 rounded-lg bg-short px-5 py-3 font-semibold text-background transition hover:opacity-90"><FiPlus /> New conversation</Link></section>
          <section className="mt-9 grid gap-4 sm:grid-cols-3">{[{ label: "Documents", value: docs.length, icon: FiFileText }, { label: "Ready to study", value: ready, icon: FiBookOpen }, { label: "Study chats", value: chats.length, icon: FiMessageSquare }].map(({ label, value, icon: Icon }) => <div key={label} className="flex items-center gap-4 rounded-2xl border border-cardBorder bg-dashBg p-5"><span className="grid size-11 place-items-center rounded-xl bg-short/10 text-xl text-short"><Icon /></span><div><p className="text-2xl font-semibold text-title">{value}</p><p className="text-sm">{label}</p></div></div>)}</section>
          <section className="mt-12"><div className="mb-4 flex items-center justify-between"><div><h2 className="text-xl font-medium text-title">Pick up where you left off</h2><p className="mt-1 text-sm">Your recent conversations.</p></div><Link to="/chat" className="text-sm font-medium text-short hover:underline">All chats</Link></div>{chats.length ? <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{chats.slice(0, 3).map((chat) => <Link key={chat.id} to={`/chat/${chat.id}`} className="group rounded-2xl border border-cardBorder bg-dashBg p-5 transition hover:border-short/50"><div className="flex items-start justify-between gap-3"><h3 className="truncate text-lg font-medium text-title">{chat.title}</h3><FiArrowRight className="mt-1 shrink-0 transition group-hover:translate-x-0.5 group-hover:text-short" /></div><p className="mt-2 line-clamp-2 min-h-10 text-sm">{chat.messages.at(-1)?.content ?? "Start a new conversation"}</p><p className="mt-4 text-xs">Updated {relativeTime(chat.updatedAt)}</p></Link>)}</div> : <div className="rounded-2xl border border-cardBorder bg-dashBg p-7 text-center"><p className="font-medium text-title">No conversations yet</p><Link to="/chat" className="mt-3 inline-flex items-center gap-2 text-sm font-medium text-short">Start your first chat <FiArrowRight /></Link></div>}</section>
          <section className="mt-12 rounded-2xl border border-cardBorder bg-cardBg p-6 sm:p-7"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="text-xl font-medium text-title">Your library</h2><p className="mt-1 text-sm">{ready} ready{processing ? ` · ${processing} processing` : ""} · {docs.length} total</p></div><Link to="/documents" className="flex items-center gap-2 rounded-lg border border-cardBorder px-4 py-2.5 text-sm font-semibold text-title transition hover:bg-navB"><FiUpload /> Manage documents</Link></div>{docs.length > 0 && <div className="mt-5 grid gap-2 sm:grid-cols-2">{docs.slice(0, 4).map((doc) => <Link to="/documents" key={doc.id} className="flex min-w-0 items-center gap-3 rounded-xl border border-cardBorder bg-dashBg px-3 py-3"><FiFileText className="shrink-0 text-short" /><span className="min-w-0 flex-1 truncate text-sm font-medium text-title">{doc.name}</span><span className={`text-xs ${doc.status === "ready" ? "text-emerald-700 dark:text-emerald-400" : "text-amber-700 dark:text-amber-400"}`}>{doc.status === "ready" ? "Ready" : "Indexing"}</span></Link>)}</div>}</section>
     </div>;
}
