import { useEffect, useRef, useState } from "react";
import { FiCheck, FiFileText, FiLoader, FiTrash2, FiUpload } from "react-icons/fi";
import { getStudyData, uploadDocument, deleteDocument } from "../services/mockBackend";
import type { StudyDocument } from "../data/mockData";

const sizeLabel = (size: number) => size >= 1_000_000 ? `${(size / 1_000_000).toFixed(1)} MB` : `${Math.max(1, Math.round(size / 1000))} KB`;
export default function Documents() {
     const [docs, setDocs] = useState<StudyDocument[]>([]); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const fileRef = useRef<HTMLInputElement>(null);
     const refresh = async () => { const next = await getStudyData(); setDocs(next.documents); };
     useEffect(() => { let mounted = true; const sync = () => { void getStudyData().then((next) => { if (mounted) setDocs(next.documents); }); }; sync(); const timer = window.setInterval(sync, 1500); return () => { mounted = false; window.clearInterval(timer); }; }, []);
     const upload = async (file?: File) => { if (!file) return; setError(""); setBusy(true); try { await uploadDocument(file); await refresh(); } catch (e) { setError(e instanceof Error ? e.message : "Could not upload this file."); } finally { setBusy(false); if (fileRef.current) fileRef.current.value = ""; } };
     const remove = async (doc: StudyDocument) => { await deleteDocument(doc.id); await refresh(); };
     return <div className="mx-auto max-w-5xl px-5 py-10 sm:px-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-medium uppercase tracking-[0.16em] text-short">Your library</p><h1 className="mt-2 text-3xl font-medium tracking-tight text-title sm:text-4xl">Documents</h1><p className="mt-2">Manage the materials your study chats can use.</p></div><button onClick={() => fileRef.current?.click()} disabled={busy} className="flex items-center gap-2 rounded-lg bg-short px-4 py-3 font-semibold text-background hover:opacity-90 disabled:opacity-60"><FiUpload />{busy ? "Uploading…" : "Upload PDF"}</button><input ref={fileRef} type="file" accept="application/pdf,.pdf" className="hidden" onChange={(e) => void upload(e.target.files?.[0])} /></div>
          <div onDragOver={(e) => e.preventDefault()} onDrop={(e) => { e.preventDefault(); void upload(e.dataTransfer.files[0]); }} className="mt-8 rounded-2xl border border-dashed border-short/50 bg-short/[0.04] p-8 text-center"><span className="mx-auto grid size-12 place-items-center rounded-xl bg-short/10 text-xl text-short"><FiUpload /></span><p className="mt-4 font-medium text-title">Drop a PDF here to add it to your library</p><p className="mt-1 text-sm">PDF files up to 20 MB. This demo stores document details only.</p>{error && <p role="alert" className="mt-3 text-sm text-red-600 dark:text-red-400">{error}</p>}</div>
          <section className="mt-8"><div className="mb-3 flex items-center justify-between"><h2 className="text-lg font-medium text-title">All documents</h2><span className="text-sm">{docs.length} {docs.length === 1 ? "file" : "files"}</span></div>
               {docs.length ? <div className="overflow-hidden rounded-2xl border border-cardBorder bg-dashBg">{docs.map((doc) => <article key={doc.id} className="flex flex-wrap items-center gap-4 border-b border-cardBorder p-4 last:border-0 sm:px-5"><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-short/10 text-xl text-short"><FiFileText /></span><div className="min-w-0 flex-1"><h3 className="truncate font-medium text-title">{doc.name}</h3><p className="mt-1 text-sm">{doc.pages ? `${doc.pages} pages · ` : ""}{sizeLabel(doc.size)} · {new Date(doc.uploadedAt).toLocaleDateString()}</p></div><span className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-xs font-medium ${doc.status === "ready" ? "bg-emerald-600/10 text-emerald-700 dark:text-emerald-400" : "bg-amber-500/15 text-amber-700 dark:text-amber-400"}`}>{doc.status === "ready" ? <FiCheck /> : <FiLoader className="animate-spin" />}{doc.status === "ready" ? "Ready" : "Indexing"}</span><button aria-label={`Delete ${doc.name}`} onClick={() => void remove(doc)} className="grid size-9 place-items-center rounded-lg text-muted hover:bg-red-500/10 hover:text-red-600"><FiTrash2 /></button></article>)}</div> : <div className="rounded-2xl border border-cardBorder bg-dashBg p-10 text-center"><p className="font-medium text-title">Your library is empty</p><p className="mt-1 text-sm">Upload your first PDF to start asking questions.</p></div>}
          </section><p className="mt-5 text-xs">Processing status is simulated locally. Uploaded file contents are not saved.</p>
     </div>;
}
